export const students = [
    {
      id: 1,
      name: "Ana Kalandadze",
      field: "Web Development",
      age: 22,
      startDate: "2023-01-15",
      experience: 2,
      completed: true,
    },
    {
      id: 2,
      name: "Giorgi Beridze",
      field: "Mobile Development",
      age: 25,
      startDate: "2022-09-10",
      experience: 3,
      completed: false,
    },
    {
      id: 3,
      name: "Nino Tsiklauri",
      field: "UI/UX Design",
      age: 21,
      startDate: "2023-03-22",
      experience: 1,
      completed: true,
    },
    {
      id: 4,
      name: "Davit Maisuradze",
      field: "Data Science",
      age: 28,
      startDate: "2022-05-18",
      experience: 4,
      completed: true,
    },
    {
      id: 5,
      name: "Tamari Lomidze",
      field: "Web Development",
      age: 23,
      startDate: "2023-02-01",
      experience: 2,
      completed: false,
    },
    {
      id: 6,
      name: "Luka Khelashvili",
      field: "Cybersecurity",
      age: 26,
      startDate: "2022-11-05",
      experience: 3,
      completed: true,
    },
    {
      id: 7,
      name: "Mariam Gigauri",
      field: "Mobile Development",
      age: 24,
      startDate: "2023-01-20",
      experience: 2,
      completed: false,
    },
    {
      id: 8,
      name: "Nikoloz Javakhishvili",
      field: "Data Science",
      age: 27,
      startDate: "2022-08-15",
      experience: 4,
      completed: true,
    },
    {
      id: 9,
      name: "Salome Tsikarishvili",
      field: "UI/UX Design",
      age: 22,
      startDate: "2023-04-10",
      experience: 1,
      completed: false,
    },
    {
      id: 10,
      name: "Irakli Dolidze",
      field: "Web Development",
      age: 25,
      startDate: "2022-10-12",
      experience: 3,
      completed: true,
    },
  ]
  